### ISSUE TITLE
Unhandled exception when running dcdg

### ISSUE THREAD

**Issue by IoanaAlexandru** [glesica/dcdg.dart#25]
When I try to run `dcdg` in my project, I get the following stack trace:
```
Unhandled exception:
NoSuchMethodError: Closure call with mismatched arguments: function 'BlockScope.elementsInBlock'
Receiver: Closure: (_SyncIterator<Element>) => bool
Tried calling: BlockScope.elementsInBlock()
Found: BlockScope.elementsInBlock(_SyncIterator<Element>) => bool
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _SyncIterable.iterator (dart:core-patch/core_patch.dart:117:45)
#2      BlockScope._defineElements (package:analyzer/src/dart/resolver/scope.dart:31:29)
#3      new BlockScope (package:analyzer/src/dart/resolver/scope.dart:27:5)
#4      ScopedVisitor.visitBlock (package:analyzer/src/generated/resolver.dart:5656:41)
#5      BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1117:49)
#6      BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1076:13)
#7      UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#8      UnifyingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:3119:55)
#9      ScopedVisitor.visitBlockFunctionBody (package:analyzer/src/generated/resolver.dart:5669:13)
#10     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1072:49)
#11     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5016:12)
#12     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#13     UnifyingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:3248:57)
#14     ScopedVisitor.visitFunctionExpression (package:analyzer/src/generated/resolver.dart:5951:13)
#15     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5010:49)
#16     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4869:26)
#17     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#18     UnifyingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:3241:59)
#19     ScopedVisitor.visitFunctionDeclarationInScope (package:analyzer/src/generated/resolver.dart:5944:11)
#20     ScopedVisitor.visitFunctionDeclaration (package:analyzer/src/generated/resolver.dart:5937:7)
#21     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4862:49)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7687:20)
#23     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2167:21)
#24     UnifyingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:3339:10)
#25     UnifyingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:3146:51)
#26     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2146:49)
#27     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:678:10)
#28     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:158:7)
#29     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#30     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:157:11)
#31     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:111:14)
#32     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#33     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:110:43)
#34     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1451:63)
#35     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#36     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#37     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1100:33)
<asynchronous suspension>
#38     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#39     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#40     ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#41     new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:46:36)
#42     findClassElements (package:dcdg/src/find_class_elements.dart:26:29)
#43     main (file:///C:/Users/sako_/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-2.0.1/bin/dcdg.dart:28:25)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1487:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1428:20)
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1100:33)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2188:24)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2118:5)
#6      ContextBuilderImpl.createContext (package:analyzer/src/dart/analysis/context_builder.dart:77:17)
#7      new AnalysisContextCollectionImpl (package:analyzer/src/dart/analysis/analysis_context_collection.dart:46:36)
#8      findClassElements (package:dcdg/src/find_class_elements.dart:26:29)
#9      main (file:///C:/Users/sako_/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-2.0.1/bin/dcdg.dart:28:25)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

I have used it before in the same project and it worked, I have no idea what's wrong now.

**Comment by glesica** [comment]
Hmm, sorry it took me so long but I’ll definitely take a look at this later today. My suspicion is that the analyzer version needs to be bumped, but that’s purely based on past experience so I’ll have to try to repro this specific exception.

**Comment by glesica** [comment]
This should no longer be a problem with the latest release because it uses a much newer version of the analyzer.
