### ISSUE TITLE
its hanging on intl

### ISSUE THREAD

**Issue by fredgrott** [glesica/dcdg.dart#43]
Its hanging on intl classes

my command lien and output errors:
PS D:\fredgrttsstuff\GithubProjects\flutter_best_practices\fbp_one> flutter pub global run dcdg -o reports\docs\diagrams\src\diagrams.puml
Unhandled exception:
Bad state: Unable to find the context to D:\fredgrttsstuff\GithubProjects\flutter_best_practices\fbp_one\lib\src\localization_gen\intl\messages_all.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:89:5)
#1      findClassElements (package:dcdg/src/find_class_elements.dart:44:39)
<asynchronous suspension>
#2      main (file:///D:/fluttersdk/myfluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/dcdg-3.1.1/bin/dcdg.dart:35:19)
<asynchronous suspension>
pub finished with exit code 255
PS D:\fredgrttsstuff\GithubProjects\flutter_best_practices\fbp_one>

**Comment by fredgrott** [comment]
here is the workaround I have to use on windows within the analysis_options.yaml file:

exclude: 
    - lib\src\localization_gen\l10n.dart
    - lib\src\localization_gen\intl\messages_all.dart


I tried quotes, did not work
I tried folder spearators the other way no go either it has to be that way on Windows.

Other path separtors work on analysis side but notthe DCDG tool side. Not sure why just as long as it freaking works which  it does.

I confirmed via powershell terminal.

Strange

**Comment by glesica** [comment]
Hmm, I don't love the way I've currently got the exclusion stuff implemented since it does the comparison only *after* it has transformed the name for the output format. This means that, for PlantUML at least, you have to using `package::Class` (for example), which is surprising since Dart doesn't use that syntax. I'm thinking about how to improve this. In the meantime, I think another good addition would be to allow exclusions simply based on relative paths, so basically "exclude this directory entirely".

**Comment by fredgrott** [comment]
@glesica  excluding the lib/src/localization_gen path would be an ideal stop-gap fix. Obvious question is would just excluding the loclaization_gen classes work? For most devs that would be the AppLocalizationDelegate and the what ever they named the other class to, in my case I use S.

**Comment by fredgrott** [comment]
The quick fix that works is to temporary relocate the localization_gen library out of the src folder when generating diagrams.

The other fix I talked about does not work.

But at least now I know a temp work around.
